os: linux

files:
  - source:  /
    destination: /home/ubuntu/flag
#    overwrite: yes # 덮어쓸 것인지

permissions:
  - object: /
    pattern: "**"
    owner: FLAG
    group: FLAG

hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 60
      runas: FLAG