spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://flag-home-rds.cfydfmrrvaec.ap-northeast-2.rds.amazonaws.com/flagDB?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: admin
    password: qwer1234!

  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true