spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: q1W@e3R$
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&characterEncoding=UTF-8

  security:
    basic:
      enabled: false


  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
        use-new-id-generator-mappings: false